name: Build Resume
on:
  push:
    tags:
      - v*
jobs:
  generate_pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: addnab/docker-run-action@v3
        with:
          image: yamlresume/yamlresume:v0.5.1
          options: -v ${{ github.workspace }}:/workspace --user 0:0
          run: yamlresume build /workspace/resume.yaml
