name: Build Resume
on:
  push:
    branches:
      - "*"
    paths:
      - "resume.yaml"
  workflow_dispatch: {}
jobs:
  generate_pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: npm install -g yamlresume
      - run: yamlresume build resume.yaml
