name: Bump version
on:
  push:
    branches:
      - main
    paths:
      - "resume.yaml"

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          TAG_PREFIX: v
